version: "3.9"

services:
  rabbitmq-managewment:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
